### ISSUE TITLE
Put in place marker/separator slides

### ISSUE THREAD

**Issue by dicook** [Abhi-1U/keynote-user2024#1]
- [x] Put the structural elements in as a slide with only a couple of words on them, eg
    [ ]  Overview of project (followed by the content slides for this section)
    [ ] Implementation details (followed by the content slides for this section)
    [ ] Demo + outline of what you are planning to show
    [ ] Some interesting findings (followed by a few slides with pictures from the articles
    [ ] How you might use these tools
    [ ] New developments
- [x] Add the quarto outline tool back in, so you can easily navigate to any slide, when questions arise
- [x] Feel free to really style as much as you want

**Comment by dicook** [comment]
- [x] Add the url to your slides as a footer on each slide
- [x] you might point people to the arXiv conversion project early in your slides, maybe near slide 3

**Comment by dicook** [comment]
- [x] Try to give concrete details on the work, rather than be too general. It's good to be specific about how you actually made things work.
- [x] At the end it would be good to have that list of things that won't work, but only after you've reported all the things that are working beautifully

**Comment by Abhi-1U** [comment]
Thanks for the feedback! 
Could not have done it without your guidance.
